-- SQLite
PRAGMA FOREIGN_keys = ON;

DROP TABLE IF EXISTS Farm;
CREATE TABLE Farm (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Region_FK TEXT NOT NULL,
);

INSERT INTO Farm VALUES (0, "Stavanger farm");


SELECT * FROM Farm;

    